#!/usr/bin/env bash

# shellcheck disable=SC2164

if [ ! -d "$WDIR" ]; then
  echo "[ERROR] task/$WDIR do not exist"
fi

if [ ! -f "$WDIR/docker-compose.yaml" ]; then
  if [ ! -L "$WDIR/docker-compose.yaml" ]; then
    ln -s "../dev/docker-compose.yaml" "$WDIR/docker-compose.yaml"
  fi
fi

for d in "dev/dc_"*; do
  target="$WDIR/$(basename $d)"
  if [ ! -f "$target" ]; then
    if [ ! -L "$target" ]; then
      ln -s "../dev/$d" "$target"
    fi
  fi
done

cd "$WDIR"
echo "###################################################################"
echo "##### [INFO] Executing docker-compose from inside '$WDIR' directory"
echo "###################################################################"
docker-compose "$@"
