dist: trusty
sudo: required
services:
- docker
addons:
  apt:
    packages:
    - docker-ce
before_install:
- "./task/setup/install/docker_install.sh"
env:
  global:
    secure: tFHXAMRSYYFzXfgl3Xmc8nDaKHBEORvydfDkBCzJpBxufbYwW0+DtPZ8O54FVJCNJ9Ud8EmE1QMdFrpI3PJ0ZBecYK3aITB2PQtyiDWgjezmjqHnOXFXefIb1mjo797wo30eDXmgFhI9d/gGbjep4PeMd9Fe6KtpCi8bDGm4fPcBkmC3zemXPNHj2HQfqmdfIVFgUz5wJxNcGGOyHkD2hkmCEX2QqRx/7pS6TPSRx+rBJEXBuwevzGyRs+FI3m38k3bpkI6q7uFOnFnJy86QO2pNhvcoD9Rzama79huGJi/oHFj3dZvaHaRD4Wp96ZLuCobPeqz1sJd7Yofb+u3DJz1eTHkt5tPq35fRJ7ksHaq8GkJL7b7lh78k9riAjWNgmgnj0gFZhkI14YjEaJY9/KvueTZiDQg3G1RWCpYyWiOT7CHUEvEb44aoCPXCdgnOOCkuThwx1bDkc6MmiauhpK6XDT5tSw7Y81BKoaX/unsS40bQ/8a+3zNaPPzLRzeWG+6Bc9X39HyrPyvGU6w1EmEDwSR7pI3RjdQndwxUoiL8uPHSYBQGbXF+Tln8KF/EilDsZNA/kkNuc6/uBNlQnw5lHsRM7dXhb5+KaXusBK8mNVeguBURPWVjJ9mYV89IbStzidu1YnGRiJilKBVF81i1HdK/RAS+4jHGQktZxlU=
before_script:
- docker build ./src/todo-view -f ./src/todo-view/Dockerfile.dev -t $DOCKER_HUB_ID/todo-view-test
- docker build ./src/todo-cache-service -f ./src/common/Dockerfile.nodejs.dev -t $DOCKER_HUB_ID/todo-cache-service-test
script:
- docker run $DOCKER_HUB_ID/todo-view-test npm test -- --browsers=ChromeHeadlessNoSandbox
  --watch=false --no-progress
- docker run $DOCKER_HUB_ID/todo-cache-service-test npm test
after_success:
- "./prod_dc build"
- echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
- "./prod_dc push"
before_deploy:
- 
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: Todo App
  env: todo-app-env
  bucket_name: elasticbeanstalk-us-east-2-277466026916
  bucket_path: todo-app
  on:
    branch: "$GITHUB_BRANCH"
  access_key_id: "$AWS_KEY_ID"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
