dist: trusty
sudo: required
services:
- docker
addons:
  apt:
    packages:
    - docker-ce
before_install:
- "./task/setup/install/docker_install.sh"
env:
  global:
    secure: lrUEMvOgigwghnYu2UaTLotOCBWcaFOxHrK/MntG4jdmiQAExspcnFaltZ9j79kEA0qfF8h2ZIcrRlRtmJnHdiCyFWezyRNZ3h4QzpcoP5/qqmCxBtwVyxc1CSIihyOp3zKa8tPT87ZTwm00p9FL708djhSyahUm5fqzYdIfTiUMpW9Wk+jHen68+sHxR7RtE8qdTZVjFykjXpTeaHOvi58ScqKbIKIfOdcueq6s0owXCp0HVq6ylTdUTGnf4UU0Yz2LifhouPwB8Oqx0GLE5Blog4awyGy8wztEw5PSeodwjffLyir00Wig1mOEnlkBRAdoK2g5pkXfM8y0Qc6iXsHki+ErrkqIiqXg58qm5fo5VmusynJ4jMguDYLp8Yp+6QZSKtNxl2vHSb9/9c1vu+u9Aa2btmy4wCEt1K/OnG39Nb0MmFeJIg6IJ22YiXp9swLWT4r4NeEKDR3zBOQkt7KImWzoOYrwvoqg96L5H05wZMXizcTLfIuUEykHN774oRElhnumBP7F51B9O3mjwtQK2MIq72Ep6UEGqCRw6gmyyIZadH2eiC8glTh6vCybDS3kFpTio4SndX0EjLIU0iIsKozBn7Gk3keGK35lQMJzuoeso3kSqYbL1m9n5UFagfH8eJZfmjKoPjLBldduGX+U0TY0szhavboFQ8OcuCI=
before_script:
- docker build ./src/todo-view -f ./src/todo-view/Dockerfile.dev -t $DOCKER_HUB_ID/todo-view-test
- docker build ./src/todo-cache-service -f ./src/common/Dockerfile.nodejs.dev -t $DOCKER_HUB_ID/todo-cache-service-test
script:
- docker run $DOCKER_HUB_ID/todo-view-test npm test -- --browsers=ChromeHeadlessNoSandbox
  --watch=false --no-progress
- docker run $DOCKER_HUB_ID/todo-cache-service-test npm test
after_success:
- "./prod_dc build"
- echo "$DOCKER_HUB_PASSWORD_ENCRYPTED" | docker login -u "$DOCKER_HUB_ID" --password-stdin
- "./prod_dc push"
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: Todo App
  env: todo-app-env
  bucket_name: elasticbeanstalk-us-east-2-277466026916
  bucket_path: todo-app
  on:
    branch: "$GITHUB_BRANCH"
  access_key_id: "$AWS_KEY_ID_ENCRYPTED"
  secret_access_key:
    secure: "$AWS_SECRET_KEY_ENCRYPTED"
