dist: trusty
sudo: required
services:
- docker
addons:
  apt:
    packages:
    - docker-ce
before_install:
- "./task/setup/install/docker_install.sh"
env:
  global:
    secure: FURGzN8o5XQojHesYUIGlByTpjDXXZGLdHuOL1agap/dAkvfbMbNv1RYhLTGpUynAQEJ7fJ8VcMhPHA6Txl49Vau9E5hZiJYuqF7SLg26vCLhYRh5lZMeOsphZBtP9aTIcardb01PD8qAzn1Q3KyyTRDGKSjhxwy115LJGnbSWy6Te+c+99wSjVComS5uMAsKqZ6vmAqnPRCVL74+FnHpsSRGc1XLVSkS7tkViMk+w8vfpNFzO4XNRnns1Yw1lapuQVVchemXbz6VvRRBrLz2UUb+Lme8I9YirTGBuR/iK8jC6rXaHpBKQxrmxACDCaWaZwyn1sMbrgSM6SPdWuUzujTiybCKiVlDKDkcKvaUuOjyO5ytWk8CLnQf3za5ssRHjWCFZG8wS5ICw8zTJkmlFJr7YZXmHDaIirQewDs+kE/0VpmuJs6x5sSDZ4MrlFkklqrg6UNKBBEn50d8nlDHXgxdFBjLYjB0Am39vksyPt0uRYTE7C7EwSi3SQBW/mmuXpuqEL/QAIeBv+DBCyfyWsyid60fenLwbo9sqRYGYq/rqLzHCvmPzahYUMSTYE4T75nvrluHJE6gNaGG69GXpN3GILHtyhtP8jfe5F4Wtm9RTmtFTu2HFlnHumK4ypJSChlkuPYB1uVqpWLHvv6rWyPrbMJuMUJEUmykW5ARXQ=
before_script:
- docker build ./src/todo-view -f ./src/todo-view/Dockerfile.dev -t $DOCKER_HUB_ID/todo-view-test
- docker build ./src/todo-cache-service -f ./src/common/Dockerfile.nodejs.dev -t $DOCKER_HUB_ID/todo-cache-service-test
script:
- docker run $DOCKER_HUB_ID/todo-view-test npm test -- --browsers=ChromeHeadlessNoSandbox
  --watch=false --no-progress
- docker run $DOCKER_HUB_ID/todo-cache-service-test npm test
after_success:
- "./prod_dockercompose build"
- echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
- "./prod_dockercompose push"
