dist: trusty
sudo: required
services:
- docker
addons:
  apt:
    packages:
    - docker-ce
before_install:
- "./task/setup/install/docker_install.sh"
env:
  global:
    secure: wEUC7+zcxool6kZbmgy5jB3L9dYxSb9ebPP6XZgpPfVOlsixpBvdCNYi+Rro7bk3ahe5XoSTMfdGPmkDi50wSPX/pgmlQmjoQTFflgKm+qYpxd/oGIcxlgAgJ7tRtxsWvSRf2LLajHEK4YztJ1TkQUS+X2LQTgh6tifhSpaXvq2cTX4p1udAn+TKIT5jnKhLrdG/QuZIwMFTOd8NyKlZoHovQa6Lkc6X79R7CokQIzAPhRzefPGu5fJnynb5EigsUTjaLnH9k54zauPTV4P7sqhDaDe92uVNKhhVbmlIjLoZe+4UGTlSLlWZ1VQkrg0IJQCWCIOburq58idP3Mt8wF3h43k+Ahdv6aYCJn+yb36+PAmjIONQCIqY8ddvmNElQSvZ82dDo64bkuHoPoL3lSw6Kz7zMuvnJwkcqcwbklNLipvFlqgyxRZHLlhxPQIkbnyA7kSuV/oCbBOqgGjJweHQgq9YNXRoOa6We/VrPHeqyvibmvoKECy+nx6KsuhIRfCfHyegmokF/DfEwKRjvK06EinYF0NHlvF6f5DZrRAnXkXTTvG2H0Wdtlc4A0P3ZDWOds815kiPscYS+tbvXYWeqvAiFbo4+LeioGpr3dUWZF61QxUjgflaZJQAiR9tpTbaCcJoba332W2/xrjch39vOy7aSA9AeR5rC8n1Uug=
before_script:
- docker build ./src/todo-view -f ./src/todo-view/Dockerfile.$BUILD_TYPE -t $DOCKER_HUB_ID/todo-view-test
- docker build ./src/todo-cache-service -f ./src/common/Dockerfile.nodejs.$BUILD_TYPE
  -t $DOCKER_HUB_ID/todo-cache-service-test
script:
- docker run $DOCKER_HUB_ID/todo-view-test npm test -- --browsers=ChromeHeadlessNoSandbox
  --watch=false --no-progress
- docker run $DOCKER_HUB_ID/todo-cache-service-test npm test
after_success:
- "./prod_dockercompose build"
- echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
- "./prod_dockercompose push"
