dist: trusty
sudo: required
services:
- docker
addons:
  apt:
    packages:
    - docker-ce
before_install:
- "./task/setup/install/docker_install.sh"
env:
  global:
    secure: ib9DnWNcl5X0FoxodpxOLRNaB7U/uLl1QLjlvPQFge63lmHsIifDdzgzijhafJf8M9I7ldgM3yimLOshy7Loxc/0qYS5xRjqPRo0DGvzO5Nprnd2RYiG1si/TjEk9esie/fHGL87sVAeYXxu9lOejJv5H3R6z8xqntLwKBk/K/SNsuXv97XZfXK+x7rZOcQ5RZSbqHBs2X5bKN2N53FuCZLiHlHUURZeKdlICz8BwybpmbBfTRlFBKrJ3ljQV5HOHjxjRRBpoBVuk3J7qis0nqNEGTYWblNkW86u8e3d/ZoORupcTiUdfjl/ax6PbXvW8q+Z12z9QarMK4Mzbww+Ws+uti3lg8S2sbQtfJluD6jKnCk3c5CPk751pHW3wO870hL04KS7T3kBa671HCRit8eyzXoQ51Q8ZoGVMICFs8Pp5POiOmHp/Kuk/io5SG3GiufbEy2djmZ6sS1Es8+MOCCGf88E2qbHfDzWcutYFrr9AWDoYdXMx9CfmGcdq0XPcx4xCBqDNiOTyveTD7ckE1gynpE2OnqklHwPgWCG/1WLkrwcwFl+rzWryYAR8IdT3Kt10r/p2A9sE3mRzV4qyDE1EZQbsnqglJBYEqjaWzRQO/M7SI7hh0f17Rm6iHfBZlmT8l5892uH2/VY7euMuA1bMj+5Bv8s1ev/R/M9yKI=
before_script:
- docker build ./src/todo-view -f ./src/todo-view/Dockerfile.$BUILD_TYPE -t $DOCKER_HUB_ID/todo-view-test
- docker build ./src/todo-cache-service -f ./src/common/Dockerfile.nodejs.$BUILD_TYPE
  -t $DOCKER_HUB_ID/todo-cache-service-test
script:
- docker run $DOCKER_HUB_ID/todo-view-test npm test -- --browsers=ChromeHeadlessNoSandbox
  --watch=false --no-progress
- docker run $DOCKER_HUB_ID/todo-cache-service-test npm test
after_success:
- "./prod_dockercompose build"
- echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
- "./prod_dockercompose push"
