dist: trusty
sudo: required
services:
- docker
addons:
  apt:
    packages:
    - docker-ce
before_install:
- "./task/setup/install/docker_install.sh"
env:
  global:
    secure: mms5Ukt58sEsgK8U+Fc4Au+Oeis0z3Zmn7F9wURfkQbeIKKu0KpF1jDR36Uc/D1YkncmVB3tv4CQM/94p7KHxI4c8AdLFvuo83ATfHDLOiKO1Z0FMG7shvEEA+8R/ZX5a/0fJpIzd52qeJ9T4VbhrGmvUkpk+OYkqtPZ1Iyj5IZoyuPGzqRve2mOQo3aJkx/v0HCNpGR/z8EnfdoWFFStxiZPx3Gn8muaIRgqkHwSOLNaYo03/11NCfBFe5v6qBVmMgtm4Xfm/bsKmVks+AAmmgqHFrqYa3+ySy7FFuv5ukHdHESi6WWxTxH93+l6kkaUF/muTgKM88IlSmijJQrvLRJUyQMaplc1xjWJ8VnVxeEdqiYQCtxQy/lyPa6z4jvfEI5BG8FVadmZ5s1mFbgpT61Tq5LGz7DkuXHjyPY2Tzq05hY6cFC+hTBjKOsE4sIke0PoE1MPjbnO1QzJH0YxcrvdSPGuL5TaAlkylohS+QRsDZPFIY7uPX3GEilQr14Rklz3ZBZg2qe6LJ51Y+AZXCPOjgwfsiyzuj8RsbRgYcu48pUtdGx/EB7FuofL7erZCUpyGSXlhf0kfkIElnWHdDWpeBkIdklreJMmihcgG1FwTAA5AqYO31L8d1MOAsPnqt46TlbMmALVTAbN3GQOAxlC2v8QyVIsKgLCXrydH0=
before_script:
- docker build ./src/todo-view -f ./src/todo-view/Dockerfile.dev -t $DOCKER_HUB_ID/todo-view-test
- docker build ./src/todo-cache-service -f ./src/common/Dockerfile.nodejs.dev -t $DOCKER_HUB_ID/todo-cache-service-test
script:
- docker run $DOCKER_HUB_ID/todo-view-test npm test -- --browsers=ChromeHeadlessNoSandbox
  --watch=false --no-progress
- docker run $DOCKER_HUB_ID/todo-cache-service-test npm test
after_success:
- "./prod_dockercompose build"
- echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
- "./prod_dockercompose push"
