dist: trusty
sudo: required
services:
- docker
addons:
  apt:
    packages:
    - docker-ce
before_install:
- "./task/setup/install/docker_install.sh"
env:
  global:
    secure: YtdAmVqc6horHMPdzv9xTutugY8MRiLqsr+qS/LlPlKN2KQaMEDtpJjgNkSo2iBe+KSY9YGfSLwUnZ7BCNA/d8RJPik/OjdoIrH24foYX+paL1qG0BkLCGJ6JQPZJIsCE80llpwGr25SPrOHGaReiFGvLUaXGehD1e6yfcvmuOA8dG3XbwNV6hycV43qEcwTu+0MMNGQDGwi5BlGvA40m1owZzLS2W9A68SyOxesSzPAETWQ3AUuZP5gtUl7L/hOyv2W27c0YGfuiE8jfjiNz5CpwVv8wV2YMtosq8b2vFsjtcFBk7bEzW9J9S2LggrJGsLUN/OQV3DjBk5GZiP8KK99x8CQ5mfbJkzr3E7CvOfFDNo3zaRE2w8dhkJlwcNVWlgBNwcYzt4g0Tc+u0lU8sl8TxRMHAYIS9BbvL7nBLbR3o5ql8dBWGuppkk9OlhuSVt8fuNvq/aSOYNGFqOIFnoL4Gmd71OTctCE+q6xEUEoEemVj6odC1RSRQoJuLmiodS8CeSxO2W6fymA3eDsaotOewONaGXeVa/ek6G8aI/jctFId2H/Yafj6lxNpE5sCEs5GR0MS4dAlajqC1ysy/UPms/82GnlcdCkOZxXh6wHkYJu0b+cBc7nH8pvWl+zubMR3/VKlVIgJVoh36aYI2KEcD8NQO5woxUaXIbVD+Y=
before_script:
- docker build ./src/todo-view -f ./src/todo-view/Dockerfile.dev -t $DOCKER_HUB_ID/todo-view-test
- docker build ./src/todo-cache-service -f ./src/common/Dockerfile.nodejs.dev -t $DOCKER_HUB_ID/todo-cache-service-test
script:
- docker run $DOCKER_HUB_ID/todo-view-test npm test -- --browsers=ChromeHeadlessNoSandbox
  --watch=false --no-progress
- docker run $DOCKER_HUB_ID/todo-cache-service-test npm test
after_success:
- "./prod_dc build"
- echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
- "./prod_dc push"
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: Todo App
  env: todo-app-env
  bucket_name: elasticbeanstalk-us-east-2-277466026916
  bucket_path: todo-app
  on:
    branch: "$GITHUB_BRANCH"
  access_key_id: "$AWS_KEY_ID"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
