dist: trusty
sudo: required
services:
  - docker

# Get Google Chrome headless browser for Angular tests
# Install latest Docker CE so we can use Dockerfile outside build context
addons:
  apt:
   packages:
      - docker-ce
# move chrome install to todo-view Dockerfile.dev (its failing here anyway)
#     - google-chrome-stable
#  sources:
#     - google-chrome

# Install any dependencies, update Docker Compose to 1.23.2 so we can use Dockerfile outside build context
before_install:
 - ./task/setup/install/docker_install.sh
# above script does what lines below
#  - docker --version
#  - docker-compose --version
#  - sudo rm /usr/local/bin/docker-compose
#  - curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` > docker-compose
#  - chmod +x docker-compose
#  - sudo mv docker-compose /usr/local/bin
#  - docker-compose --version
#install:

# Build development images for test
before_script:
  - docker build ./src/todo-view -f ./src/todo-view/Dockerfile.dev -t $GITHUB_USER/todo-view-test
  - docker build ./src/todo-cache-service -f ./src/common/Dockerfile.nodejs.dev -t $GITHUB_USER/todo-cache-service-test

# Run some tests
script:
  - docker run $GITHUB_USER/todo-view-test npm test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
  - docker run $GITHUB_USER/todo-cache-service-test npm test

after_success:
  # Build Production Images for deployment
  - ./prod_dc build
  # Login to Docker Hub
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
  # Take the built production images and push to Docker Hub
  - ./prod_dc push

deploy:
  provider: elasticbeanstalk
  region: <YOUR-AWS_REGION>
  app: <YOUR-EB_APP_NAME>
  env: <YOUR-EB_ENV_NAME>
  bucket_name: <YOUR-EB_S3_BUCKET_NAME>
  bucket_path: todo-app
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY