apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ${NAMESPACE}
  name: todo-storage-service
  labels:
    todo-app-deployment: todo-storage-service
spec:
  replicas: 2
  selector:
      matchLabels:
        todo-app-pod: todo-storage-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        todo-app-pod: todo-storage-service
    spec:
      restartPolicy: Always
      containers:
      - image: {{ .Values.DOCKER_HUB_ID }}/${STORAGE_SERVICE_IMAGE}
        name: todo-storage-service
        envFrom:
          - configMapRef:
              name: todo-config
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: todo-secret
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: ${STORAGE_SERVICE_TARGET_PORT}
        resources:
          limits:
            memory: "${STORAGE_SERVICE_LIMITS_MEMORY}"
