apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ${NAMESPACE}
  name: todo-search-ingestion
  labels:
    todo-app-deployment: todo-search-ingestion
spec:
  replicas: 1
  selector:
      matchLabels:
        todo-app-pod: todo-search-ingestion
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        todo-app-pod: todo-search-ingestion
    spec:
      restartPolicy: Always
      initContainers:
      - name: init-rabbitmq
        image: busybox
        command: ['sh', '-c', 'until nslookup todo-rabbitmq; do echo waiting for RabbitMQ; sleep 2; done;']
      - name: init-elastic
        image: busybox
        command: ['sh', '-c', 'until nslookup todo-elastic; do echo waiting for ElasticSearch; sleep 2; done;']
      containers:
      - name: todo-search-ingestion
        image: {{ .Values.DOCKER_HUB_ID }}/${SEARCH_INGESTION_IMAGE}
        envFrom:
          - configMapRef:
              name: todo-config
        resources:
          limits:
            memory: ${SEARCH_INGESTION_LIMITS_MEMORY}
