apiVersion: v1
kind: ConfigMap
metadata:
  namespace: "${NAMESPACE}"
  name: todo-config
data:
  REDIS_HOST: "${REDIS_HOST}"
  REDIS_CLUSTER_PORT: "${REDIS_PORT}"
  ELASTICSEARCH_HOST: "${ELASTICSEARCH_HOST}"
  ELASTICSEARCH_CLUSTER_PORT: "${ELASTICSEARCH_PORT}"
  POSTGRES_HOST: "${POSTGRES_HOST}"
  POSTGRES_CLUSTER_PORT: "${POSTGRES_PORT}"
  POSTGRES_DB: "${POSTGRES_DB}"
  POSTGRES_USER: "${POSTGRES_USER}"
  RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
  RABBITMQ_URL: "${RABBITMQ_URL}"
  CACHE_SERVICE_URL: "${CACHE_SERVICE_URL}"
  SEARCH_SERVICE_URL: "${SEARCH_SERVICE_URL}"
  STORAGE_SERVICE_URL: "${STORAGE_SERVICE_URL}"