apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.resolved.yml --replicas=2 --verbose
      --out config --verbose
    kompose.version: 1.19.0 (f63a961c)
    namespace: todo
  creationTimestamp: null
  labels:
    io.kompose.service: todo-cache-service
  name: todo-cache-service
spec:
  replicas: 2
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.resolved.yml --replicas=2 --verbose
          --out config --verbose
        kompose.version: 1.19.0 (f63a961c)
        namespace: todo
      creationTimestamp: null
      labels:
        io.kompose.service: todo-cache-service
    spec:
      containers:
      - env:
        - name: REDIS_HOST
          value: todo-redis
        - name: REDIS_PORT
          value: "6379"
        image: onceawaken/todo-cache-service:1.0
        name: todo-cache-service
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "134217728"
          requests:
            memory: "104857600"
      restartPolicy: Always
status: {}
