dist: xenial
sudo: required
language: python
python: 3.7
install:
- pip install -r requirements.txt
services:
- docker
addons:
  apt:
    packages:
    - docker-ce
before_install:
- bash ./setup/fix/no_public_key_fix.sh
- bash ./setup/install/docker_install.sh
env:
  global:
    secure: NVZteLHGhcbn/RYDYoh4kZYtIX8cSYbuW5fbETXXez0+1CIcKBzpqQIL26s7wj5GtB88j7VFNIOYHD3c4Y+r7sWB09GslNUZJYRicpNLuruLbw5E8Bjgax5Gt7LPHVcZJPz51XBh8wi/X+J3L50N5yfrxxCgCmq4QSB245HmMObQIK0UA2NuGZfZdgJcE4jzn+zTlUpbh3AhtCTH0Yi9cPnb2OQdydYiAmqHVLpca4swz3an2qhTQZsHlwYUaYljIZjEa+KCYUwQd/prdKKtT8hBUv1Nfy7Oelsp3OthtSff7WllaN3dFmVKSJfSfhJX/VMYdbu7iJ5bQbR6RXixNFg55pkUbhgFOT65TQq9zmeryjLh7YuVMYzSyCSR3cYei+weFiQNH13ADH4zTpIaoMzHyCoXY+LpCvCwNahYMk4ALjwO9wvvw0zI+5q6CROdhLGrNyQnxRdcX6XYs2ghf50K1ZY8QLBbD208JlJr/oMbQ/Hg4J3x1yfPIXiB+9AVOqI7LXbuwKMaYChWjux20Zr3mFaeGZa2CXPhngioq6A6B9XUClrziei4maJxpm7IsqMezA8ZMCqdgy6/ZX5kkNY+LweTGPBoMI0zMXfb3rAu7mC7xkEHZgiH9CbP2mNdbO63N2I47cdIUrAslr9WMMlZXWtg4xPFtrGVwErCWOM=
before_script:
- docker build ./todo-app/src/todo-view -f ./todo-app/src/todo-view/Dockerfile.dev
  -t $DOCKER_HUB_ID/todo-view-test
- docker build ./todo-app/src/todo-cache-service -f ./todo-app/src/common/Dockerfile.nodejs.dev
  -t $DOCKER_HUB_ID/todo-cache-service-test
script:
- docker run $DOCKER_HUB_ID/todo-view-test npm test -- --browsers=ChromeHeadlessNoSandbox
  --watch=false --no-progress
- docker run $DOCKER_HUB_ID/todo-cache-service-test npm test
after_success:
- python3.7 main.py DC BUILD
- echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
- python3.7 main.py DC PUSH
