FROM postgres:11.2

ENV POSTGRES_USER todo
ENV POSTGRES_PASSWORD todo1234
ENV POSTGRES_DB todo

RUN mkdir /probes
COPY readiness.sh /probes/readiness.sh
COPY liveness.sh /probes/liveness.sh
RUN chmod +x probes/*.sh

COPY create_todo_table.sql /docker-entrypoint-initdb.d/