version: "3.7"

services:

  todo-postgres:
    image: ${DOCKER_HUB_ID}/todo-postgres:1.0

  todo-cache-ingestion:
    image: ${DOCKER_HUB_ID}/todo-cache-ingestion:1.0
    #we are no longer executing by root, but with user node
    command: sh /home/node/app/start.sh

  todo-cache-service:
    image: ${DOCKER_HUB_ID}/todo-cache-service:1.0

  todo-search-ingestion:
    image: ${DOCKER_HUB_ID}/todo-search-ingestion:1.0
    command: sh /home/node/app/start.sh

  todo-search-service:
    image: ${DOCKER_HUB_ID}/todo-search-service:1.0
    command: sh /home/node/app/start.sh

  todo-storage-ingestion:
    image: ${DOCKER_HUB_ID}/todo-storage-ingestion:1.0
    command: sh /home/node/app/start.sh

  todo-storage-service:
    image: ${DOCKER_HUB_ID}/todo-storage-service:1.0

  todo-api-gateway:
    image: ${DOCKER_HUB_ID}/todo-api-gateway:1.0
    command: sh /home/node/app/start.sh

  todo-view:
    image: ${DOCKER_HUB_ID}/todo-view:1.0
    # dc is appending to array, not overriding it,
    # so we can not use 4200 again
    ports:
      - 4201:8080 # to match todo-view/custom.nginx

  todo-proxy:
    image: ${DOCKER_HUB_ID}/todo-proxy:1.0
