apiVersion: v1
kind: Service
metadata:
  namespace: ${NAMESPACE}
  name: todo-cache-service
  labels:
    todo-app-service: todo-cache-service
spec:
  type: ClusterIP
  selector:
    todo-app-pod: todo-cache-service
  ports:
  - name: ${CACHE_SERVICE_PORT_NAME}
    port: ${CACHE_SERVICE_PORT}
    targetPort: ${CACHE_SERVICE_TARGET_PORT}

