apiVersion: v1
kind: Secret
metadata:
  namespace: ${NAMESPACE}
  name: todo-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
