apiVersion: v1
kind: Service
metadata:
  namespace: ${NAMESPACE}
  name: todo-api-gateway
  labels:
    todo-app-service: todo-api-gateway
spec:
  type: ClusterIP
  selector:
    todo-app-pod: todo-api-gateway
  ports:
  - name: ${APIGATEWAY_PORT_NAME}
    port: ${APIGATEWAY_PORT}
    targetPort: ${APIGATEWAY_TARGET_PORT}

