apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.override.yml
      -f docker-compose.limits.yml -f kompose.override.yml --replicas=2 --verbose
      --out converted
    kompose.version: 1.19.0 (f63a961c)
    namespace: todo
  creationTimestamp: null
  labels:
    io.kompose.service: todo-storage-service
  name: todo-storage-service
spec:
  replicas: 2
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.override.yml
          -f docker-compose.limits.yml -f kompose.override.yml --replicas=2 --verbose
          --out converted
        kompose.version: 1.19.0 (f63a961c)
        namespace: todo
      creationTimestamp: null
      labels:
        io.kompose.service: todo-storage-service
    spec:
      containers:
      - env:
        - name: POSTGRES_DATABASE
        - name: POSTGRES_HOST
        - name: POSTGRES_PASSWORD
        - name: POSTGRES_PORT
        - name: POSTGRES_USER
        image: /todo-storage-service:1.0
        name: todo-storage-service
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
