apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.override.yml
      -f docker-compose.limits.yml -f kompose.override.yml --replicas=2 --verbose
      --out converted
    kompose.version: 1.19.0 (f63a961c)
    namespace: todo
  creationTimestamp: null
  labels:
    io.kompose.service: todo-api-gateway
  name: todo-api-gateway
spec:
  replicas: 2
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.override.yml
          -f docker-compose.limits.yml -f kompose.override.yml --replicas=2 --verbose
          --out converted
        kompose.version: 1.19.0 (f63a961c)
        namespace: todo
      creationTimestamp: null
      labels:
        io.kompose.service: todo-api-gateway
    spec:
      containers:
      - args:
        - sh
        - /home/node/app/start.sh
        env:
        - name: CACHE_SERVICE_URL
        - name: RABBITMQ_URL
        - name: SEARCH_SERVICE_URL
        - name: STORAGE_SERVICE_URL
        image: /todo-api-gateway:1.0
        name: todo-api-gateway
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
