apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data-pv
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: ${POSTGRES_PV_CAPACITY_STORAGE}
  hostPath:
    path: ${POSTGRES_PV_HOSY_PATH}
