apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ${NAMESPACE}
  name: postgres-data-pvc
spec:
#  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: ${POSTGRES_PV_CAPACITY_STORAGE}
