apiVersion: v1
kind: Service
metadata:
  namespace: ${NAMESPACE}
  name: todo-postgres
  labels:
    todo-app-service: todo-postgres
spec:
  type: ClusterIP
  selector:
    todo-app-pod: todo-postgres
  ports:
    - name: ${POSTGRES_PORT_NAME}
      port: ${POSTGRES_PORT}
      targetPort:  ${POSTGRES_TARGET_PORT}

