apiVersion: v1
kind: Service
metadata:
  namespace: todo
  name: todo-view
  labels:
    todo-app-service: todo-view
spec:
  type: ClusterIP
  selector:
    todo-app-pod: todo-view
  ports:
  - name: http
    port:  8080
    targetPort: 8080

