apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.override.yml
      -f docker-compose.limits.yml -f kompose.override.yml --replicas=2 --verbose
      --out converted
    kompose.version: 1.19.0 (f63a961c)
    namespace: todo
  creationTimestamp: null
  labels:
    io.kompose.service: todo-redis
  name: todo-redis
spec:
  replicas: 2
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.override.yml
          -f docker-compose.limits.yml -f kompose.override.yml --replicas=2 --verbose
          --out converted
        kompose.version: 1.19.0 (f63a961c)
        namespace: todo
      creationTimestamp: null
      labels:
        io.kompose.service: todo-redis
    spec:
      containers:
      - image: redis:5.0.3
        name: todo-redis
        ports:
        - containerPort: 6379
        resources: {}
      restartPolicy: Always
status: {}
