apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: postgres-data-pv
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath:
    path: "/home/data/kubedata/todo/postgres"
